baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Autoclient AI- Crawl Emails & Leads and Auto Send Bulk Email Campaigns"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/screenshot-2024-03-24-at-03.44.37.png"]